// pokeApp/src/pages/Login.jsx
import React from "react";
import { useState } from "react";
import { signInWithEmailAndPassword } from "firebase/auth";
import { auth } from "../firebase";
import { useNavigate } from "react-router-dom";

function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");

  const navigate = useNavigate();

  async function handleLogin(e) {
    e.preventDefault();
    try {
      await signInWithEmailAndPassword(auth, email, password);
      navigate("/");
    } catch (err) {
      setError("Error al iniciar sesión");
    }
  }

  return (
    <div className="container">
      <div className="content-box">
      <h2>Iniciar Sesión</h2>

      <form onSubmit={handleLogin}>
        <input
          type="email"
          placeholder="Email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
        />
        <br /><br />
        <input
          type="password"
          placeholder="Contraseña"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
        />
        <br /><br />
        <button type="submit">Entrar</button>
      </form>

      {error && <p>{error}</p>}
      </div>
    </div>
  );
}

export default Login;

// todoAppMultiusuario/src/pages/Login.vue
<template>
  <div class="container">
    <div class="form">
      <h2>Login</h2>

      <input v-model="email" type="email" placeholder="Email" />
      <input v-model="password" type="password" placeholder="Contraseña" />

      <button @click="login">Entrar</button>
      <button @click="loginGoogle">Entrar con Google</button>
    </div>
  </div>
</template>

<script>
import { signInWithEmailAndPassword, signInWithPopup } from 'firebase/auth'
import { auth, googleProvider } from '../firebase'
import { store } from '../store'

export default {
  data() {
    return {
      email: '',
      password: ''
    }
  },
  methods: {
    async login() {
      const result = await signInWithEmailAndPassword(
        auth,
        this.email,
        this.password
      )
      store.setUser(result.user)
      this.$router.push('/recordatorios')
    },
    async loginGoogle() {
      const result = await signInWithPopup(auth, googleProvider)
      store.setUser(result.user)
      this.$router.push('/recordatorios')
    }
  }
}
</script>
